### ISSUE TITLE
Would you be in favour of a PR to add a couple of features?

### ISSUE THREAD

**Issue by sdd** [sbosnick/semantic-release-rust#24]
I like the idea of making use of the existing semantic-release ecosystem that semantic-release-rust goes for. I really want to start using it but there are a couple of steps that I also need to perform as part of the release step that I don't think are handled currently:

1. Updating Cargo.toml to have the correct URL for the [html_root_url attribute](https://rust-lang.github.io/api-guidelines/documentation.html#crate-sets-html_root_url-attribute-c-html-root)
2. A find / replace functionality to allow automatic updating of documentation that contains the package version string (ie the [pre-release-replacements](https://github.com/sunng87/cargo-release/blob/HEAD/docs/reference.md#prepost-release-replacements) functionality that cargo-release provides), for things like code examples in the README.md and src/lib.rs inline documentation.

Would you be welcoming of a PR to add this?

**Comment by sbosnick** [comment]
I would welcome PR's to add these two features. I would probably be easier to review them if they were 2 separate PR's rather then one big one but I would be happy to accept either approach.

How were you thinking of handling configuration of the find / replace functionality? `cargo-release` appears to have 4 or 5 different places that it looks for its configuration. I'm not sure that that many different options is really helpful. I would generally want to avoid using the CLI (since I hope to eventually wrap the library up in some form of JavaScript package to release on npm).

Whatever we choose for the location for the configuration information may grow over time as other features get added so I would make a good choice up front if possible.

**Comment by sdd** [comment]
> How were you thinking of handling configuration of the find / replace functionality? cargo-release appears to have 4 or 5 different places that it looks for its configuration.

Good point - I was thinking purely of cli args as per the --no-dirty flag for `semantic-release-rust publish`, but find/replace seems ill-suited to being configured this way due to the need for escaping and having multiple search regexes and replace strings; it would be a bit clunky.

I worked around not having this in semantic-release-rust by creating a short shell script and adding an extra entry for `@semantic-release/exec` to my .releaserc.yml which calls the shell script, passing in the crate name and the next release version string.

release.yml:
```yml
# replace "your-crate-name" with the name of your crate
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/github'
  - - '@semantic-release/exec'
    - verifyConditionsCmd: "semantic-release-rust verify-conditions"
      prepareCmd: "semantic-release-rust prepare ${nextRelease.version}"
      publishCmd: "semantic-release-rust publish --no-dirty=false"
  - - '@semantic-release/exec'
    - prepareCmd: "./replace-doc-version-strings.sh your-crate-name ${nextRelease.version}"
  - - '@semantic-release/git'
    - assets:
      - README.md
      - src/lib.rs
      - Cargo.toml
      - Cargo.lock
```

replace-doc-version-strings.sh:
```bash
#!/usr/bin/env bash
set -eu

# rewrite the version string in any embedded examples of Cargo.toml entries inside src/lib.rs and write to new-lib.rs
sed "s%^//! $1 = \".*\"%//! $1 = \"$2\"%" < src/lib.rs > new-lib.rs

# rewrite the version string inside the html_root_url attribute inside new-lib.rs and overwrite src/lib.rs with the result
sed "s%docs\.rs/$1/.*\"%docs.rs/$1/$2\"%" < new-lib.rs > src/lib.rs
rm new-lib.rs

# do the same as the first sed call, but for Cargo.toml examples in README.md
sed "s%^$1 = \".*\"%$1 = \"$2\"%" < README.md > new-README.md
mv new-README.md README.md

```

I think it may make more sense to do all of this (ie what semantic-release-rust does currently, as well as the text replacement) in a @semantic-release/rust or @semantic-release/cargo npm library. That would allow re-use of the existing JS libs of the semantic-release ecosystem, eliminate the @semantic-release/exec wrapping, and allow configuration by the conventional semantic-release config files.
